//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/Input/IA_ValveController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input/IA_ValveController.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @IA_ValveController: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @IA_ValveController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""IA_ValveController"",
    ""maps"": [
        {
            ""name"": ""ValveInteraction"",
            ""id"": ""f368e364-d2ff-4aec-8b0e-d6b306ce8fa4"",
            ""actions"": [
                {
                    ""name"": ""Unpossess"",
                    ""type"": ""Button"",
                    ""id"": ""7a489cc2-742a-40d4-8476-53ec27be2919"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveHandle"",
                    ""type"": ""Button"",
                    ""id"": ""c68af48e-7c8e-4c7b-9ece-03abf96004ba"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReleaseHandle"",
                    ""type"": ""Button"",
                    ""id"": ""9ae60274-c949-4836-9997-501d10e93696"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d7e63270-93f6-435f-b34e-a9de2d456e89"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unpossess"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e4dd63d-b308-473a-9751-b60c9d82aa8d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveHandle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a1edaef-8b8d-4620-a1e3-17b986ad9284"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReleaseHandle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ValveInteraction
        m_ValveInteraction = asset.FindActionMap("ValveInteraction", throwIfNotFound: true);
        m_ValveInteraction_Unpossess = m_ValveInteraction.FindAction("Unpossess", throwIfNotFound: true);
        m_ValveInteraction_MoveHandle = m_ValveInteraction.FindAction("MoveHandle", throwIfNotFound: true);
        m_ValveInteraction_ReleaseHandle = m_ValveInteraction.FindAction("ReleaseHandle", throwIfNotFound: true);
    }

    ~@IA_ValveController()
    {
        UnityEngine.Debug.Assert(!m_ValveInteraction.enabled, "This will cause a leak and performance issues, IA_ValveController.ValveInteraction.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ValveInteraction
    private readonly InputActionMap m_ValveInteraction;
    private List<IValveInteractionActions> m_ValveInteractionActionsCallbackInterfaces = new List<IValveInteractionActions>();
    private readonly InputAction m_ValveInteraction_Unpossess;
    private readonly InputAction m_ValveInteraction_MoveHandle;
    private readonly InputAction m_ValveInteraction_ReleaseHandle;
    /// <summary>
    /// Provides access to input actions defined in input action map "ValveInteraction".
    /// </summary>
    public struct ValveInteractionActions
    {
        private @IA_ValveController m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ValveInteractionActions(@IA_ValveController wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ValveInteraction/Unpossess".
        /// </summary>
        public InputAction @Unpossess => m_Wrapper.m_ValveInteraction_Unpossess;
        /// <summary>
        /// Provides access to the underlying input action "ValveInteraction/MoveHandle".
        /// </summary>
        public InputAction @MoveHandle => m_Wrapper.m_ValveInteraction_MoveHandle;
        /// <summary>
        /// Provides access to the underlying input action "ValveInteraction/ReleaseHandle".
        /// </summary>
        public InputAction @ReleaseHandle => m_Wrapper.m_ValveInteraction_ReleaseHandle;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ValveInteraction; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ValveInteractionActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ValveInteractionActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ValveInteractionActions" />
        public void AddCallbacks(IValveInteractionActions instance)
        {
            if (instance == null || m_Wrapper.m_ValveInteractionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ValveInteractionActionsCallbackInterfaces.Add(instance);
            @Unpossess.started += instance.OnUnpossess;
            @Unpossess.performed += instance.OnUnpossess;
            @Unpossess.canceled += instance.OnUnpossess;
            @MoveHandle.started += instance.OnMoveHandle;
            @MoveHandle.performed += instance.OnMoveHandle;
            @MoveHandle.canceled += instance.OnMoveHandle;
            @ReleaseHandle.started += instance.OnReleaseHandle;
            @ReleaseHandle.performed += instance.OnReleaseHandle;
            @ReleaseHandle.canceled += instance.OnReleaseHandle;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ValveInteractionActions" />
        private void UnregisterCallbacks(IValveInteractionActions instance)
        {
            @Unpossess.started -= instance.OnUnpossess;
            @Unpossess.performed -= instance.OnUnpossess;
            @Unpossess.canceled -= instance.OnUnpossess;
            @MoveHandle.started -= instance.OnMoveHandle;
            @MoveHandle.performed -= instance.OnMoveHandle;
            @MoveHandle.canceled -= instance.OnMoveHandle;
            @ReleaseHandle.started -= instance.OnReleaseHandle;
            @ReleaseHandle.performed -= instance.OnReleaseHandle;
            @ReleaseHandle.canceled -= instance.OnReleaseHandle;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ValveInteractionActions.UnregisterCallbacks(IValveInteractionActions)" />.
        /// </summary>
        /// <seealso cref="ValveInteractionActions.UnregisterCallbacks(IValveInteractionActions)" />
        public void RemoveCallbacks(IValveInteractionActions instance)
        {
            if (m_Wrapper.m_ValveInteractionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ValveInteractionActions.AddCallbacks(IValveInteractionActions)" />
        /// <seealso cref="ValveInteractionActions.RemoveCallbacks(IValveInteractionActions)" />
        /// <seealso cref="ValveInteractionActions.UnregisterCallbacks(IValveInteractionActions)" />
        public void SetCallbacks(IValveInteractionActions instance)
        {
            foreach (var item in m_Wrapper.m_ValveInteractionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ValveInteractionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ValveInteractionActions" /> instance referencing this action map.
    /// </summary>
    public ValveInteractionActions @ValveInteraction => new ValveInteractionActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ValveInteraction" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ValveInteractionActions.AddCallbacks(IValveInteractionActions)" />
    /// <seealso cref="ValveInteractionActions.RemoveCallbacks(IValveInteractionActions)" />
    public interface IValveInteractionActions
    {
        /// <summary>
        /// Method invoked when associated input action "Unpossess" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUnpossess(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveHandle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveHandle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ReleaseHandle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReleaseHandle(InputAction.CallbackContext context);
    }
}
